### ISSUE TITLE
Don't compile in the new version of Arduino IDE

### ISSUE THREAD

**Issue by simontorres** [signout/Arduino-DS1340-library#1]
Hello, I'm trying to use your library for one of my projects and, while testing it, using the examples provided it gives this errors.

/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp: In member function 'uint8_t RTC_DS1340::isrunning()':
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:133: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:137: error: 'class TwoWire' has no member named 'receive'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp: In static member function 'static void RTC_DS1340::adjust(const DateTime&)':
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:143: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:144: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:145: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:146: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:147: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:148: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:149: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:150: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:151: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp: In static member function 'static DateTime RTC_DS1340::enabletricklecharger()':
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:157: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:158: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp: In static member function 'static DateTime RTC_DS1340::disabletricklecharger()':
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:164: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp: In member function 'uint8_t RTC_DS1340::isrunning()':
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:165: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:133: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp: In static member function 'static DateTime RTC_DS1340::enableFTout()':
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:137: error: 'class TwoWire' has no member named 'receive'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:171: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp: In static member function 'static void RTC_DS1340::adjust(const DateTime&)':
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:175: error: 'class TwoWire' has no member named 'receive'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:143: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:177: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:144: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:178: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:145: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:146: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp: In static member function 'static DateTime RTC_DS1340::disableFTout()':
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:147: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:184: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:148: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:188: error: 'class TwoWire' has no member named 'receive'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:149: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:190: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:150: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:191: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:151: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp: In static member function 'static DateTime RTC_DS1340::now()':
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:197: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp: In static member function 'static DateTime RTC_DS1340::enabletricklecharger()':
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:201: error: 'class TwoWire' has no member named 'receive'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:157: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:202: error: 'class TwoWire' has no member named 'receive'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:158: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:203: error: 'class TwoWire' has no member named 'receive'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:204: error: 'class TwoWire' has no member named 'receive'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp: In static member function 'static DateTime RTC_DS1340::disabletricklecharger()':
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:205: error: 'class TwoWire' has no member named 'receive'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:164: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:206: error: 'class TwoWire' has no member named 'receive'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:165: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:207: error: 'class TwoWire' has no member named 'receive'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp: In static member function 'static DateTime RTC_DS1340::enableFTout()':
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp: In static member function 'static void RTC_Millis::adjust(const DateTime&)':
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:171: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:218: error: 'millis' was not declared in this scope
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:175: error: 'class TwoWire' has no member named 'receive'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp: In static member function 'static DateTime RTC_Millis::now()':
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:177: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:222: error: 'millis' was not declared in this scope
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:178: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp: In static member function 'static DateTime RTC_DS1340::disableFTout()':
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:184: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:188: error: 'class TwoWire' has no member named 'receive'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:190: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:191: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp: In static member function 'static DateTime RTC_DS1340::now()':
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:197: error: 'class TwoWire' has no member named 'send'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:201: error: 'class TwoWire' has no member named 'receive'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:202: error: 'class TwoWire' has no member named 'receive'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:203: error: 'class TwoWire' has no member named 'receive'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:204: error: 'class TwoWire' has no member named 'receive'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:205: error: 'class TwoWire' has no member named 'receive'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:206: error: 'class TwoWire' has no member named 'receive'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:207: error: 'class TwoWire' has no member named 'receive'
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp: In static member function 'static void RTC_Millis::adjust(const DateTime&)':
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:218: error: 'millis' was not declared in this scope
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp: In static member function 'static DateTime RTC_Millis::now()':
/Users/simon/sketchbook/libraries/rtcDS1340/DS1340lib.cpp:222: error: 'millis' was not declared in this scope

**Comment by simontorres** [comment]
I just find the solution.
First, Wire has some new wording...

Wire.send is now Wire.write
Wire.receive is now Wire.read

You must change it on the .cpp file.

Then for the millis error you just need to:
#include <Arduino.h> in the header of the .cpp file again.

And as I'm working with the Arduino UNO the SDA and SCL port are different in the examples here it says:
SCL to port A0
SDA to port A1
And the correct ones (for the UNO) are:
SCL 5
SDA 4

I hope you find this info useful!
Saludos from Chile!

**Comment by Sdowell0022** [comment]
dude, simontorres!  Just had the wording issue with wire.receive...  fixed.  Thank you!

**Comment by rxtx-rpud** [comment]
@simontorres Compadre,de todas las vueltas que me di en Internet un compatriota tenía que ayudar jaja! Gracias!

**Comment by 10310258** [comment]
Wprogram.h => Arduino.h
All -- Wire.send => Wire.write
All -- Wire.receive => Wire.read
Static uint8_t daysInMonth => const uint8_t daysInMonth
This helped me to get time on rtc m41t00 also.

**Comment by eperezf** [comment]
Gracias @simontorres! Tuve el mismo problema 7 años más tarde jaja!

**Comment by signout** [comment]
This issue has been fixed now.
